class FontConstant {
  static const int FONT_SMALL = 1;
  static const int FONT_MID = 2;
  static const int FONT_BIG = 3;

  static final int FONT_CONTENT_COLOR_DAY = 0xFF666666;
  static final int FONT_CONTENT_COLOR_NIGHT = 0xFF6A6F7D;
  static final double FONT_CONTENT_SMALL = 16.0;
  static final double FONT_CONTENT_MID = 18.0;
  static final double FONT_CONTENT_BIG = 20.0;

  static final int FONT_SUMMARY_COLOR_DAY = 0xFF666666;
  static final int FONT_SUMMARY_COLOR_NIGHT = 0xFF7B8199;
  static final double FONT_SUMMARY_SMALL = 14.0;
  static final double FONT_SUMMARY_MID = 16.0;
  static final double FONT_SUMMARY_BIG = 18.0;

  static final double FONT_CONTENT_TITLE_SIZE = 21.0;
  static final int FONT_CONTENT_TITLE_COLOR_DAY = 0xFF222222;
  static final int FONT_CONTENT_TITLE_COLOR_NIGHT = 0xFF8992A3;

  static final double FONT_AUTHOR_SIZE = 12.0;
  static final int FONT_AUTHOR_COLOR_DAY = 0xFF999999;
  static final int FONT_AUTHOR_COLOR_NIGHT = 0xFF5C616E;

  static final FONT_BOTTOMBAR_BACKGROUNDCOLOR_DAY = 0xFA1C2023;
  static final FONT_BOTTOMBAR_BACKGROUNDCOLOR_NIGHT = 0xFF1E1E28;

  static final int FONT_AUTHOR_VERTICAL_LINE_COLOR_DAY = 0xFFE4E4E4;
  static final int FONT_AUTHOR_VERTICAL_LINE_COLOR_NIGHT = 0xFF5C616E;

  static final int FONT_SUMMARY_BACKGROUND_COLOR_NIGHT = 0x107E7E96;
  static final int FONT_SUMMARY_BACKGROUND_COLOR_DAY = 0x60EAEAEA;

  static final double FONT_AUTHOR_BELOW_SIZE = 18.0;
  static final int FONT_AUTHOR_BELOW_COLOR_NIGHT = 0xFF9F9F9F;
  static final int FONT_AUTHOR_BELOW_COLOR_DAY = 0xFF464646;

  static final double FONT_AUTHOR_BRIEF_SIZE = 16.0;
  static final int FONT_AUTHOR_BRIEF_COLOR = 0xFF777777;

  static final int FONT_LOGIN_BACKGROUND_COLOR_NIGHT = 0xFF2C2C3A;
  static final int FONT_LOGIN_BACKGROUND_COLOR_DAY = 0xFFEE5656;

  static final double FONT_USERNAME_SIZE = 14.0;
  static final int FONT_USERNAME_COLOR_NIGHT = 0xFF818699;
  static final int FONT_USERNAME_COLOR_DAY = 0xFFFFFFFF;

  static final double FONT_SETTING_ITEM_SIZE = 14.0;

  static final int FONT_LINE_SHIXIN_COLOR_DAY = 0x4D636363;
  static final int FONT_LINE_SHIXIN_COLOR_NIGHT = 0x4D636363;

  static final int FONT_TITLE_BACKGROUND_COLOR_DAY = 0xFFF6F6F6;
  static final int FONT_TITLE_BACKGROUND_COLOR_NIGHT = 0xFF262633;

  static final int FONT_TITLE_COLOR_DAY = 0xFF1C2023;
  static final int FONT_TITLE_COLOR_NIGHT = 0xFF707684;

  static final int FONT_ARTICLE_BACKGROUND_COLOR_NIGHT = 0xFF262626;
  static final int FONT_ARTICLE_BACKGROUND_COLOR_DAY = 0xFF1C2023;

  static final int FONT_ARTICLE_BACKGROUND_COLOR_FILM = 0xFFEE5656;
  static final int FONT_ARTICLE_BACKGROUND_COLOR_NOVEL = 0xFF;
  static final int FONT_ARTICLE_BACKGROUND_COLOR_DIAGRAM = 0xFF787878;

  static final int FONT_FEEDBACK_COLOR_NIGHT = 0xFF5C616E;
  static final int FONT_FEEDBACK_COLOR_DAY = 0xFF666666;

  static final int FONT_FAVORITEDATETV_COLOR_NIGHT = 0x96FFFFFF;
  static final int FONT_FAVORITEDATETV_COLOR_DAY = 0xFFFFFFFF;

  static final int FONT_FAVORITETITLE_COLOR_NIGHT = 0xFF7B8199;
  static final int FONT_FAVORITETITLE_COLOR_DAY = 0xFF505050;

  static final int FONT_FAVORITESUMMART_COLOR_NIGHT = 0xFF5C616E;
  static final int FONT_FAVORITESUMMART_COLOR_DAY = 0xFFB4B4B4;

  static final int FONT_MAIN_BACKGROUND_COLOR_NIGHT = 0xFF1E1E29;
  static final int FONT_MAIN_BACKGROUND_COLOR_DAY = 0xFFFFFFFF;

  static final int FONT_SIZE_NORMAL_COLOR_NIGHT = 0xFF7B8199;
  static final int FONT_SIZE_NORMAL_COLOR_DAY = 0xFF666666;

  static final int FONT_SETTINGVERSION_COLOR_NIGHT = 0xFF565A68;
  static final int FONT_SETTINGVERSION_COLOR_DAY = 0xFFD5D5d5;

  static final int FONT_BRIEF_COLOR_NIGHT = 0xFF858D9E;
  static final int FONT_BRIEF_COLOR_DAY = 0xFF222222;
}